name: Razmod
main: me.Razish.Razmod.Razmod
version: 0.0.9c

commands:
    players:
        description: List the online players
        usage: /players
    wb:
        description: Give yourself a workbench
        usage: /wb
    seed:
        description: Displays the seed of a given world
        usage: /seed
#    fb:
#        description: Shoot a fireball!
#        usage: /fb
#    stackraz:
#        description: Stack the unused tools in your inventory
#        usage: /stackraz